rvm:
  - 1.9.3
  - 2.0.0

env:
  - DB=sqlite
  - DB=mysql

before_script: ruby ./script/ci/travis_before_build.rb
script: bundle exec rake iqvoc:setup:generate_secret_token db:drop db:create db:migrate test RAILS_ENV=test

branches:
  only:
    - master

notifications:
  recipients:
    - iqvoc@innoq.com
