rvm:
  - 1.9.3
  - 2.0.0

env:
  - DB=sqlite
  - DB=mysql

before_script: ./script/ci/travis_before_build.rb
script: ./script/ci/travis_build.rb

branches:
  only:
    - master

notifications:
  recipients:
    - iqvoc@innoq.com
