development:
  adapter: postgresql
  database: iqvoc_compound_forms_development
  username: root
  password:
  encoding: utf8

test:
  adapter: postgresql
  database: iqvoc_compound_forms_test
  username: root
  password:
  encoding: utf8

production:
  adapter: postgresql
  database: iqvoc_compound_forms_production
  username: root
  password:
  encoding: utf8
